# Generated by Django 4.2 on 2023-10-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('EXPRESS', 'express delivery'), ('REGULAR', 'regular delivery')], default='REGULAR', max_length=10, verbose_name='delivery type'),
        ),
    ]
