# Generated by Django 4.2 on 2023-10-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsale',
            name='value',
            field=models.IntegerField(default=0, verbose_name='sale value'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='value',
            field=models.IntegerField(default=0, verbose_name='sale value'),
        ),
        migrations.AlterField(
            model_name='discountproductgroup',
            name='value',
            field=models.IntegerField(default=0, verbose_name='sale value'),
        ),
    ]
