# Generated by Django 4.2 on 2023-10-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_cartitem_discount_cartitem_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'CartItem', 'verbose_name_plural': 'CartItems'},
        ),
    ]
