"""Ключи для кеширования сайта"""

DETAIL_PRODUCT_KEY = 'DETAIL_PRODUCT:'
PRODUCTS_KEY = 'PRODUCTS'
CATEGORY_LIST_KEY = 'CATEGORY_LIST'
BANNER_LIST_KEY = 'BANNER_LIST'
TOP_PRODUCT_LIST_KEY = 'TOP_PRODUCT_LIST'
CATALOG_CATEGORY = 'CATALOG_CATEGORY:'
OFFER_DAY = 'OFFER_DAY'
