# Generated by Django 4.2 on 2023-09-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='', max_length=48, verbose_name='Full name'),
        ),
    ]
