# Generated by Django 4.2 on 2023-09-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
