# Generated by Django 4.2 on 2023-10-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_price_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('key', models.CharField(max_length=15, verbose_name='cache key')),
                ('value', models.PositiveIntegerField(default=86400, verbose_name='cache value')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
