# Generated by Django 4.2 on 2023-10-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cachesetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachesetup',
            name='key',
            field=models.CharField(max_length=30, verbose_name='cache key'),
        ),
    ]
